# 顶层服务定义
services:
  # 后端服务定义
  backend:
    # 运行的镜像标签
    image: backend/ai-think:1.0.0
    # 使用主机网络模式 (提升性能与安全性)
    network_mode: host
    # 镜像构建配置
    build:
      context: ..
      dockerfile: backend/Dockerfile
    # 重启策略
    restart: unless-stopped
    # 容器环境变量
    environment:
      TZ: "Asia/Shanghai"
    # 挂载卷
    volumes:
      - ./data/logs:/app/logfile # 宿主机日志目录 -> 容器日志目录
      - ./data/uploads:/app/uploads # 宿主机上传目录 -> 容器上传目录
      - ./data/conf/config.docker.yaml:/app/conf/config.docker.yaml:ro # 宿主机配置文件 -> 容器配置（只读）

  # 前端服务定义
  frontend:
    # 运行的镜像标签
    image: frontend/ai-think:1.0.0
    # 使用主机网络模式
    network_mode: host
    # 镜像构建配置
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    # 重启策略
    restart: unless-stopped
    # 依赖服务
    depends_on:
      - backend
